BASSPATH = $(HOME)/build/bass
### Generated by Winemaker


SRCDIR                = .
SUBDIRS               =
DLLS                  =
EXES                  = h2cdplay_wine.exe



### Common settings

CEXTRA                = -mno-cygwin
CXXEXTRA              = -mno-cygwin
RCEXTRA               =
INCLUDE_PATH          = -I$(BASSPATH)
DLL_PATH              =
LIBRARY_PATH          = -L$(BASSPATH)
LIBRARIES             = -lbass -Wl,-rpath,$(BASSPATH)


### h2cdplay_wine.exe sources and settings

h2cdplay_wine_exe_MODULE= h2cdplay_wine.exe
h2cdplay_wine_exe_C_SRCS= h2cdplay.c
h2cdplay_wine_exe_CXX_SRCS=
h2cdplay_wine_exe_RC_SRCS=
h2cdplay_wine_exe_LDFLAGS= -mwindows \
			-mno-cygwin
h2cdplay_wine_exe_DLL_PATH=
h2cdplay_wine_exe_DLLS= odbc32 \
			ole32 \
			oleaut32 \
			winspool
h2cdplay_wine_exe_LIBRARY_PATH=
h2cdplay_wine_exe_LIBRARIES= uuid

h2cdplay_wine_exe_OBJS= $(h2cdplay_wine_exe_C_SRCS:.c=.o) \
			$(h2cdplay_wine_exe_CXX_SRCS:.cpp=.o) \
			$(h2cdplay_wine_exe_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(h2cdplay_wine_exe_C_SRCS)
CXX_SRCS              = $(h2cdplay_wine_exe_CXX_SRCS)
RC_SRCS               = $(h2cdplay_wine_exe_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(EXES:%=%.so)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(EXES:%=%.so) $(EXES:%.exe=%)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH)

$(h2cdplay_wine_exe_MODULE).so: $(h2cdplay_wine_exe_OBJS)
	$(CC) $(h2cdplay_wine_exe_LDFLAGS) -o $@ $(h2cdplay_wine_exe_OBJS) $(h2cdplay_wine_exe_LIBRARY_PATH) $(DEFLIB) $(h2cdplay_wine_exe_DLLS:%=-l%) $(h2cdplay_wine_exe_LIBRARIES:%=-l%)


